# Generated by Django 4.2.1 on 2023-05-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("publish", "Publish"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
