# Generated by Django 4.2.1 on 2023-05-09 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name_plural": "All Posts"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
