# Generated by Django 4.2.1 on 2023-05-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blogpost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
