# Generated by Django 4.2.1 on 2023-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogpost_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
